services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  directus:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    # https://github.com/directus/docs/issues/331#issuecomment-3190266688
    healthcheck:
      test: ["CMD-SHELL", "[ $$(wget -q -O - ${DIRECTUS_URL}/server/ping) = 'pong' ]"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s
  
  directus-sync:
    image: node:22-alpine
    depends_on:
      directus:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./directus-config:/directus/directus-config
      - ./directus-sync.config.cjs:/directus/directus-sync.config.cjs
    working_dir: /directus
    command: >
      sh -c "
        echo 'PWD:' && pwd;
        echo 'Directory contents:' && ls -la;
        echo 'Config file:' && ls -la directus-sync.config.cjs || true;
        npx directus-sync push;
      "
    restart: "no"

volumes:
  db_data:
